name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: prepare postgres
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql --command="ALTER USER postgres WITH PASSWORD '123456'"
          sudo -u postgres createdb task-manager
          PGPASSWORD=123456 psql --username=postgres --host=localhost --list timetable
      - name: npm install, build
        run: |
          make setup
          make build
        env:
          DATABASE_URL: postgres://postgres:123456@localhost/task-manager
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
